### PR TITLE
Gcc8 fixes

### PR DESCRIPTION
**Pull request by mabrand**
These make it build on:

Ubuntu 18.10
gcc (Ubuntu 8.2.0-7ubuntu1) 8.2.0
linux 4.18.12-041812-generic

So far it works fine too.

### CODE REVIEW

**Comment by mabrand** [comment]
Would you like to add these commits to your pull request?
https://github.com/cilynx/rtl88x2BU_WiFi_linux_v5.2.4.4_26334.20180126_COEX20171012-5044/pull/1

**Comment by MaxG87** [comment]
Thank you very much for your Pull Request. I really appreciate that.

However, I am not able to reproduce the issues. I am on Ubuntu Testing, using Kernel 4.18.0 and GCC 8.2. I even tried activating -O3. Have you applied any other changes here?

Also, while I like the patch for the off-by-one bug, I need some days to inspect the second one.

I would appreciate very much if you could polish your commit messages a bit. I like the style guide by Tim Pope (https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html). Especially, please do not paste GCC's output but briefly explain the issue and its solution. It would be great if you could force-push in the end.

**Comment by MaxG87** [comment]
I had a closer look at the off-by-one bug. It seemed to me that the proposed patch only silenced GCC but did not resolve the issue. I just pushed a new branch, ensure_string_termination, which putted one commit on top of the 'fork'-branch. The commit message should explain and resolve the issue.

Could you please give it a try and report whether it works for you too?

**Comment by MaxG87** [comment]
I was able to reproduce the issues on Ubuntu 18.04. Weirdly, the GCC version is 8.2.0, as in Debian Testing. Thank you very much for making me aware.

However, I decided to fix the issues a bit differently from what was proposed. This, I do not merge.

**Pull request closed without merging**
